"""workspaces

Revision ID: 4bf3044f6b80
Revises: 
Create Date: 2026-03-25 04:56:55.377289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf3044f6b80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Pure SQL — each op.execute() is a single statement (asyncpg requirement).
    # Drop everything if leftover from a failed run
    op.execute("DROP TABLE IF EXISTS work_pauses CASCADE")
    op.execute("DROP TABLE IF EXISTS work_sessions CASCADE")
    op.execute("DROP TABLE IF EXISTS invite_codes CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS workspaces CASCADE")
    op.execute("DROP TYPE IF EXISTS user_status CASCADE")
    op.execute("DROP TYPE IF EXISTS user_role CASCADE")
    op.execute("DROP TYPE IF EXISTS session_status CASCADE")

    # ENUM types
    op.execute("CREATE TYPE user_status AS ENUM ('OFFLINE', 'WORKING', 'PAUSED')")
    op.execute("CREATE TYPE user_role AS ENUM ('USER', 'ADMIN', 'SUPERADMIN')")
    op.execute("CREATE TYPE session_status AS ENUM ('ACTIVE', 'PAUSED', 'COMPLETED')")

    # Tables
    op.execute("""CREATE TABLE workspaces (
        id BIGSERIAL PRIMARY KEY,
        name VARCHAR(200) NOT NULL,
        owner_telegram_id BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
    )""")

    op.execute("""CREATE TABLE users (
        id BIGSERIAL PRIMARY KEY,
        telegram_id BIGINT NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        status user_status NOT NULL,
        role user_role NOT NULL,
        workspace_id BIGINT REFERENCES workspaces(id),
        created_at TIMESTAMPTZ NOT NULL
    )""")
    op.execute("CREATE UNIQUE INDEX ix_users_telegram_id ON users (telegram_id)")
    op.execute("CREATE INDEX ix_users_workspace_id ON users (workspace_id)")

    op.execute("""CREATE TABLE invite_codes (
        id BIGSERIAL PRIMARY KEY,
        code VARCHAR(8) NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        role VARCHAR(20) NOT NULL,
        workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
        created_by BIGINT NOT NULL REFERENCES users(id),
        used_by BIGINT REFERENCES users(id),
        used_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL
    )""")
    op.execute("CREATE UNIQUE INDEX ix_invite_codes_code ON invite_codes (code)")
    op.execute("CREATE INDEX ix_invite_codes_workspace_id ON invite_codes (workspace_id)")

    op.execute("""CREATE TABLE work_sessions (
        id BIGSERIAL PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id),
        started_at TIMESTAMPTZ NOT NULL,
        ended_at TIMESTAMPTZ,
        status session_status NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
    )""")
    op.execute("CREATE INDEX ix_work_sessions_user_id ON work_sessions (user_id)")
    op.execute("CREATE INDEX ix_work_sessions_user_status ON work_sessions (user_id, status)")

    op.execute("""CREATE TABLE work_pauses (
        id BIGSERIAL PRIMARY KEY,
        session_id BIGINT NOT NULL REFERENCES work_sessions(id) ON DELETE CASCADE,
        paused_at TIMESTAMPTZ NOT NULL,
        resumed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL
    )""")
    op.execute("CREATE INDEX ix_work_pauses_session_id ON work_pauses (session_id)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_pauses_session_id'), table_name='work_pauses')
    op.drop_table('work_pauses')
    op.drop_index('ix_work_sessions_user_status', table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_user_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_invite_codes_workspace_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
    # Удаляем пользовательские ENUM-типы, если они существуют
    op.execute("DROP TYPE IF EXISTS user_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS user_role CASCADE;")
    op.execute("DROP TYPE IF EXISTS session_status CASCADE;")
